=== beehive-innovation/rain-protocol/opmeta_schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$ref": "#/definitions/OpMeta",
    "definitions": {
        "OpMeta": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string",
                    "title": "Opcode Name",
                    "description": "The primary word used to identify the opcode",
                    "pattern": "^[A-Za-z_][0-9A-Za-z-_]*$"
                },
                "desc": {
                    "type": "string",
                    "title": "Opcode Description",
                    "description": "Describes what the opcode does briefly"
                },
                "operand": {
                    "anyOf": [
                        {
                            "type": "integer",
                            "const": 0
                        },
                        {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/OperandArg"
                            },
                            "minItems": 1
                        }
                    ],
                    "title": "Opcode Operand",
                    "description": "Data required in order to calculate and format the operand"
                },
                "inputs": {
                    "$ref": "#/definitions/InputMeta",
                    "title": "Opcode Inputs",
                    "description": "Data required to specify the inputs the opcode"
                },
                "outputs": {
                    "$ref": "#/definitions/OutputMeta",
                    "title": "Opcode Outputs",
                    "description": "Data required to specify the outputs the opcode"
                },
                "aliases": {
                    "type": "array",
                    "items": {
                        "type": "string",
                        "pattern": "^[A-Za-z_][0-9A-Za-z-_]*$"
                    },
                    "title": "Opcode Aliases",
                    "description": "Extra word used to identify the opcode"
                }
            },
            "required": [
                "name",
                "desc",
                "operand",
                "inputs",
                "outputs"
            ],
            "additionalProperties": false,
            "title": "Opcode Metadata",
            "description": "Schema for opcodes metadata used by Rainlang parser and formatter"
        },
        "OperandArg": {
            "type": "object",
            "properties": {
                "bits": {
                    "type": "array",
                    "items": {
                        "type": "integer",
                        "minimum": 0,
                        "maximum": 15
                    },
                    "minItems": 2,
                    "maxItems": 2,
                    "title": "Allocated Operand Bits",
                    "description": "Specifies the bits to allocate to this operand argument"
                },
                "name": {
                    "type": "string",
                    "title": "Operand Argument Name",
                    "description": "Name of the operand argument. Argument with the name of \"inputs\" is reserved so that it wont be be typed inside <> and its value needed to construct the operand will be the number of items inside the opcode's parens (computation will apply to this value if provided)",
                    "pattern": "^[A-Za-z0-9_][A-Za-z0-9-_\\s]*[A-Za-z0-9-_]$"
                },
                "desc": {
                    "type": "string",
                    "title": "Operand Argument Description",
                    "description": "Description of the operand argument"
                },
                "computation": {
                    "type": "string",
                    "title": "Allocated Operand Bits Computation",
                    "description": "Specifies any arithmetical operation that needs to be applied on the value of this operand argument. The \"arg\" keyword is reserved for accessing the value of this operand argument, example: \"(arg + 1) * 2\""
                },
                "validRange": {
                    "type": "array",
                    "items": {
                        "anyOf": [
                            {
                                "type": "array",
                                "items": {
                                    "type": "integer",
                                    "minimum": 0,
                                    "maximum": 65535
                                },
                                "minItems": 1,
                                "maxItems": 1
                            },
                            {
                                "type": "array",
                                "items": {
                                    "type": "integer",
                                    "minimum": 0,
                                    "maximum": 65535
                                },
                                "minItems": 2,
                                "maxItems": 2
                            }
                        ]
                    },
                    "title": "Operand Argument Range",
                    "description": "Determines the valid range of the operand argument before any computation applied. For an Operand Argument named \"Inputs\" it defines the valid length of items inside opcode's parens. For example an operand argument can be any range between 1 - 10: [[1, 10]] or an operand argument can only be certain exact number: [[2], [3], [9]], meaning it can only be 2 or 3 or 9"
                }
            },
            "required": [
                "bits",
                "name"
            ],
            "additionalProperties": false
        },
        "InputMeta": {
            "anyOf": [
                {
                    "type": "integer",
                    "const": 0
                },
                {
                    "type": "object",
                    "properties": {
                        "parameters": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "properties": {
                                    "name": {
                                        "type": "string",
                                        "title": "Input Parameter Name",
                                        "description": "Name of the input parameter",
                                        "pattern": "^[A-Za-z0-9_][A-Za-z0-9-_\\s]*[A-Za-z0-9-_]$"
                                    },
                                    "desc": {
                                        "type": "string",
                                        "title": "Input Parameter Description",
                                        "description": "Description of the input parameter"
                                    },
                                    "spread": {
                                        "type": "boolean",
                                        "title": "Parameter Spread",
                                        "description": "Specifies if an argument is dynamic in length, default is false, so only needs to be defined if an argument is spread."
                                    }
                                },
                                "required": [
                                    "name"
                                ],
                                "additionalProperties": false
                            },
                            "title": "Parameters",
                            "description": "Data type for opcode's inputs parameters, the length determines the number of inputs for constant (non-computed) inputs."
                        },
                        "bits": {
                            "type": "array",
                            "items": {
                                "type": "integer",
                                "minimum": 0,
                                "maximum": 15
                            },
                            "minItems": 2,
                            "maxItems": 2,
                            "title": "Inputs-Allocated Operand Bits",
                            "description": "Specifies bits of the operand allocated for number of inputs. Determines the number of inputs for a computed opcode inputs. Required only for computed (non-constant) inputs"
                        },
                        "computation": {
                            "type": "string",
                            "title": "Inputs-Allocated Operand Bits Computation",
                            "description": "Specifies any arithmetical operation that needs to be applied on value of the extracted operand bits. The \"bits\" keyword is reserved for accessing the exctraced value, example: \"(bits + 1) * 2\". Required only for computed (non-constant) inputs"
                        }
                    },
                    "required": [
                        "parameters"
                    ],
                    "additionalProperties": false
                }
            ]
        },
        "OutputMeta": {
            "anyOf": [
                {
                    "type": "integer",
                    "minimum": 0
                },
                {
                    "type": "object",
                    "properties": {
                        "bits": {
                            "type": "array",
                            "items": {
                                "type": "integer",
                                "minimum": 0,
                                "maximum": 15
                            },
                            "minItems": 2,
                            "maxItems": 2,
                            "title": "Outputs-Allocated Operand Bits",
                            "description": "Specifies bits of the operand allocated for number of outputs. Determines the number of outputs for a computed opcode outputs. Required only for computed (non-constant) outputs"
                        },
                        "computation": {
                            "type": "string",
                            "title": "Outputs-Allocated Operand Bits Computation",
                            "description": "Specifies any arithmetical operation that needs to be applied on value of the extracted operand bits. The \"bits\" keyword is reserved for accessing the exctraced value, example: \"(bits + 1) * 2\". Required only for computed (non-constant) outputs"
                        }
                    },
                    "additionalProperties": false
                }
            ]
        }
    }
}

=== beehive-innovation/rain-protocol/contracts/interpreter/ops/math/logic/EagerIf.opmeta.json
{
    "name": "EAGER_IF",
    "desc": "Takes 3 items from the stack and check if the first item is non-zero the inserts the second item into the stack, else inserts the 3rd item",
    "operand": [],
    "inputs": {
        "parameters": [
            {
                "name": "Condition",
                "desc": "The condition to evaluate"
            },
            {
                "name": "Pass Statement",
                "desc": "The value to stack if the condition is non-zero/true"
            },
            {
                "name": "Fail Statement",
                "desc": "The value to stack if the condition is zero/false"
            }
        ]
    },
    "outputs": 1,
    "aliases": ["EAGERIF", "IF"]
}

=== beehive-innovation/rain-protocol/contracts/interpreter/ops/math/Sub.opmeta.json
{
    "name": "SUB",
    "desc": "Inserts the subtraction of N values taken from the stack into the stack",
    "operand": [
        {
            "name": "Inputs",
            "bits": [0, 7],
            "validRange": [[2, 255]]
        }
    ],
    "inputs": {
        "bits": [0, 7],
        "parameters": [
            {
                "name": "Input",
                "spread": true
            }
        ]
    },
    "outputs": 1,
    "aliases": ["MINUS", "-"]
}

=== beehive-innovation/rain-protocol/contracts/interpreter/ops/core/ContextRow.opmeta.json
{
    "name": "CONTEXT_ROW",
    "desc": "Inserts a context cell into the stack by reading the column from operand and row from stack",
    "operand": [
        {
            "name": "Column",
            "desc": "context column",
            "bits": [0, 7]
        }
    ],
    "inputs": {
        "parameters": [
            {
                "name": "Row"
            }
        ]
    },
    "outputs": 1
}

=== beehive-innovation/rain-protocol/contracts/interpreter/ops/math/OpMin.opmeta.json
{
  "name": "min",
  "desc": "Inserts the minimum of N values taken from the stack into the stack",
  "operand": [
    {
      "name": "Inputs",
      "bits": [0, 7],
      "validRange": [[2, 255]]
    }
  ],
  "inputs": {
    "bits": [0, 7],
    "parameters": [
      {
        "name": "Input",
        "spread": true
      }
    ]
  },
  "outputs": 1,
  "aliases": ["minimum", "min-of", "minof"]
}

=== beehive-innovation/rain-protocol/contracts/interpreter/ops/core/Set.opmeta.json
{
    "name": "SET",
    "desc": "Write a key/value pair taken from stack and write into contract storage",
    "operand": [],
    "inputs": {
        "parameters": [
            {
                "name": "Key"
            },
            {
                "name": "Value"
            }
        ]
    },
    "outputs": 0,
    "aliases": ["WRITE"]
}

=== beehive-innovation/rain-protocol/contracts/interpreter/ops/erc721/OpERC721OwnerOf.opmeta.json
{
  "name": "erc721-owner-of",
  "desc": "Get the owner of an ERC20 token of an account and insert it into the stack",
  "operand": 0,
  "inputs": {
    "parameters": [
      {
        "name": "Token Address"
      },
      {
        "name": "Token Id"
      }
    ]
  },
  "outputs": 1,
  "aliases": ["erc721ownerof", "ierc721ownerof"]
}

=== beehive-innovation/rain-protocol/contracts/interpreter/ops/tier/SaturatingDiff.opmeta.json
{
    "name": "SATURATING_DIFF",
    "desc": "Inserts the saturating difference of 2 reports taken from the stack into the stack and prevents reverts if the result below zero",
    "operand": 0,
    "inputs": {
        "parameters": [
            {
                "name": "1st Value"
            },
            {
                "name": "2nd Value2"
            }
        ]
    },
    "outputs": 1,
    "aliases": ["SAT_DIFF", "SATDIFF", "SATURATINGDIFF"]
}

=== beehive-innovation/rain-protocol/contracts/interpreter/ops/tier/OpUpdateTimesForTierRange.opmeta.json
{
  "name": "update-times-for-tier-range",
  "desc": "Inserts the result of updating the range of tiers of a report taken from stack by a value taken from the stack into the stack",
  "operand": [
    {
      "name": "Start Tier",
      "desc": "the starting tier to update",
      "bits": [0, 3],
      "validRange": [[0, 8]]
    },
    {
      "name": "End Tier",
      "desc": "the ending tier to update",
      "bits": [4, 7],
      "validRange": [[0, 8]]
    }
  ],
  "inputs": {
    "parameters": [
      {
        "name": "Update Timestamp",
        "desc": "the timestamp to update tier range to"
      },
      {
        "name": "Report",
        "desc": "the report to update its tier range"
      }
    ]
  },
  "outputs": 1,
  "aliases": [
    "updatetimesfortierrange",
    "update-tier-range",
    "updatetierrange",
    "update-tiers",
    "updatetiers",
    "update-report",
    "updatereport"
  ]
}
