=== beehive-innovation/rain-protocol/opmeta_schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$ref": "#/definitions/OpMeta",
    "definitions": {
        "OpMeta": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string",
                    "title": "Opcode Name",
                    "description": "The primary word used to identify the opcode",
                    "pattern": "^[A-Za-z_][0-9A-Za-z-_]*$"
                },
                "desc": {
                    "type": "string",
                    "title": "Opcode Description",
                    "description": "Describes what the opcode does briefly"
                },
                "operand": {
                    "anyOf": [
                        {
                            "type": "integer",
                            "const": 0
                        },
                        {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/OperandArg"
                            },
                            "minItems": 1
                        }
                    ],
                    "title": "Opcode Operand",
                    "description": "Data required in order to calculate and format the operand"
                },
                "inputs": {
                    "$ref": "#/definitions/InputMeta",
                    "title": "Opcode Inputs",
                    "description": "Data required to specify the inputs the opcode"
                },
                "outputs": {
                    "$ref": "#/definitions/OutputMeta",
                    "title": "Opcode Outputs",
                    "description": "Data required to specify the outputs the opcode"
                },
                "aliases": {
                    "type": "array",
                    "items": {
                        "type": "string",
                        "pattern": "^[A-Za-z_][0-9A-Za-z-_]*$"
                    },
                    "title": "Opcode Aliases",
                    "description": "Extra word used to identify the opcode"
                }
            },
            "required": [
                "name",
                "desc",
                "operand",
                "inputs",
                "outputs"
            ],
            "additionalProperties": false,
            "title": "Opcode Metadata",
            "description": "Schema for opcodes metadata used by Rainlang parser and formatter"
        },
        "OperandArg": {
            "type": "object",
            "properties": {
                "bits": {
                    "type": "array",
                    "items": {
                        "type": "integer",
                        "minimum": 0,
                        "maximum": 15
                    },
                    "minItems": 2,
                    "maxItems": 2,
                    "title": "Allocated Operand Bits",
                    "description": "Specifies the bits to allocate to this operand argument"
                },
                "name": {
                    "type": "string",
                    "title": "Operand Argument Name",
                    "description": "Name of the operand argument. Argument with the name of \"inputs\" is reserved so that it wont be be typed inside <> and its value needed to construct the operand will be the number of items inside the opcode's parens (computation will apply to this value if provided)",
                    "pattern": "^[A-Za-z0-9_][A-Za-z0-9-_\\s]*[A-Za-z0-9-_]$"
                },
                "desc": {
                    "type": "string",
                    "title": "Operand Argument Description",
                    "description": "Description of the operand argument"
                },
                "computation": {
                    "type": "string",
                    "title": "Allocated Operand Bits Computation",
                    "description": "Specifies any arithmetical operation that needs to be applied on the value of this operand argument. The \"arg\" keyword is reserved for accessing the value of this operand argument, example: \"(arg + 1) * 2\""
                },
                "validRange": {
                    "type": "array",
                    "items": {
                        "anyOf": [
                            {
                                "type": "array",
                                "items": {
                                    "type": "integer",
                                    "minimum": 0,
                                    "maximum": 65535
                                },
                                "minItems": 1,
                                "maxItems": 1
                            },
                            {
                                "type": "array",
                                "items": {
                                    "type": "integer",
                                    "minimum": 0,
                                    "maximum": 65535
                                },
                                "minItems": 2,
                                "maxItems": 2
                            }
                        ]
                    },
                    "title": "Operand Argument Range",
                    "description": "Determines the valid range of the operand argument before any computation applied. For an Operand Argument named \"Inputs\" it defines the valid length of items inside opcode's parens. For example an operand argument can be any range between 1 - 10: [[1, 10]] or an operand argument can only be certain exact number: [[2], [3], [9]], meaning it can only be 2 or 3 or 9"
                }
            },
            "required": [
                "bits",
                "name"
            ],
            "additionalProperties": false
        },
        "InputMeta": {
            "anyOf": [
                {
                    "type": "integer",
                    "const": 0
                },
                {
                    "type": "object",
                    "properties": {
                        "parameters": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "properties": {
                                    "name": {
                                        "type": "string",
                                        "title": "Input Parameter Name",
                                        "description": "Name of the input parameter",
                                        "pattern": "^[A-Za-z0-9_][A-Za-z0-9-_\\s]*[A-Za-z0-9-_]$"
                                    },
                                    "desc": {
                                        "type": "string",
                                        "title": "Input Parameter Description",
                                        "description": "Description of the input parameter"
                                    },
                                    "spread": {
                                        "type": "boolean",
                                        "title": "Parameter Spread",
                                        "description": "Specifies if an argument is dynamic in length, default is false, so only needs to be defined if an argument is spread."
                                    }
                                },
                                "required": [
                                    "name"
                                ],
                                "additionalProperties": false
                            },
                            "title": "Parameters",
                            "description": "Data type for opcode's inputs parameters, the length determines the number of inputs for constant (non-computed) inputs."
                        },
                        "bits": {
                            "type": "array",
                            "items": {
                                "type": "integer",
                                "minimum": 0,
                                "maximum": 15
                            },
                            "minItems": 2,
                            "maxItems": 2,
                            "title": "Inputs-Allocated Operand Bits",
                            "description": "Specifies bits of the operand allocated for number of inputs. Determines the number of inputs for a computed opcode inputs. Required only for computed (non-constant) inputs"
                        },
                        "computation": {
                            "type": "string",
                            "title": "Inputs-Allocated Operand Bits Computation",
                            "description": "Specifies any arithmetical operation that needs to be applied on value of the extracted operand bits. The \"bits\" keyword is reserved for accessing the exctraced value, example: \"(bits + 1) * 2\". Required only for computed (non-constant) inputs"
                        }
                    },
                    "required": [
                        "parameters"
                    ],
                    "additionalProperties": false
                }
            ]
        },
        "OutputMeta": {
            "anyOf": [
                {
                    "type": "integer",
                    "minimum": 0
                },
                {
                    "type": "object",
                    "properties": {
                        "bits": {
                            "type": "array",
                            "items": {
                                "type": "integer",
                                "minimum": 0,
                                "maximum": 15
                            },
                            "minItems": 2,
                            "maxItems": 2,
                            "title": "Outputs-Allocated Operand Bits",
                            "description": "Specifies bits of the operand allocated for number of outputs. Determines the number of outputs for a computed opcode outputs. Required only for computed (non-constant) outputs"
                        },
                        "computation": {
                            "type": "string",
                            "title": "Outputs-Allocated Operand Bits Computation",
                            "description": "Specifies any arithmetical operation that needs to be applied on value of the extracted operand bits. The \"bits\" keyword is reserved for accessing the exctraced value, example: \"(bits + 1) * 2\". Required only for computed (non-constant) outputs"
                        }
                    },
                    "additionalProperties": false
                }
            ]
        }
    }
}

=== beehive-innovation/rain-protocol/contracts/interpreter/ops/core/Call.opmeta.json
{
    "name": "CALL",
    "desc": "Takes some items from the stack and runs a source with sub-stack and puts the results back to the stack",
    "operand": [
        {
            "name": "Inputs",
            "bits": [0, 3],
            "validRange": [[0, 15]]
        },
        {
            "name": "Output Size",
            "desc": "number of outputs",
            "bits": [4, 7],
            "validRange": [[0, 15]]
        },
        {
            "name": "Source Index",
            "desc": "index of the source to run",
            "bits": [8, 11],
            "validRange": [[0, 15]]
        }
    ],
    "inputs": {
        "bits": [0, 3],
        "parameters": [
            {
                "name": "Input",
                "spread": true
            }
        ]
    },
    "outputs": {
        "bits": [4, 7]
    },
    "aliases": ["FUNCTION", "FN"]
}

=== beehive-innovation/rain-protocol/contracts/interpreter/ops/erc20/snapshot/OpERC20SnapshotBalanceOfAt.opmeta.json
{
  "name": "erc20-snapshot-balance-of-at",
  "desc": "Get the snapshot balance of an ERC20 token of an account and insters it into the stack",
  "operand": 0,
  "inputs": {
    "parameters": [
      {
        "name": "Token Address"
      },
      {
        "name": "Account"
      },
      {
        "name": "Snapshot Id"
      }
    ]
  },
  "outputs": 1,
  "aliases": ["erc20snapshotbalanceofat", "ierc20snapshotbalanceofat"]
}

=== beehive-innovation/rain-protocol/contracts/interpreter/ops/erc20/snapshot/ERC20SnapshotBalanceOfAt.opmeta.json
{
    "name": "ERC20_SNAPSHOT_BALANCE_OF_AT",
    "desc": "Get the snapshot balance of an ERC20 token of an account and insters it into the stack",
    "operand": [],
    "inputs": {
        "parameters": [
            {
                "name": "Token Address"
            },
            {
                "name": "Account"
            },
            {
                "name": "Snapshot Id"
            }
        ]
    },
    "outputs": 1,
    "aliases": [
        "ERC20SNAPSHOTBALANCEOFAT",
        "IERC20SNAPSHOTBALANCEOFAT"
    ]
}

=== beehive-innovation/rain-protocol/contracts/interpreter/ops/core/DoWhile.opmeta.json
{
  "name": "do-while",
  "desc": "Runs a while loop on number of items taken from a stack until a conditions is met",
  "operand": [
    {
      "name": "inputs",
      "bits": [0, 3],
      "validRange": [[1, 15]]
    },
    {
      "name": "source-index",
      "desc": "index of the source to run",
      "bits": [8, 11]
    }
  ],
  "inputs": {
    "bits": [0, 3],
    "parameters": [
      {
        "name": "input",
        "spread": true
      },
      {
        "name": "condition",
        "desc": "condition of while loop"
      }
    ]
  },
  "outputs": {
    "bits": [0, 3]
  },
  "aliases": ["while"]
}

=== beehive-innovation/rain-protocol/contracts/interpreter/ops/erc20/ERC20BalanceOf.opmeta.json
{
  "name": "ERC20_BALANCE_OF",
  "desc": "Get the balance of an ERC20 token of an account and insert it into the stack",
  "operand": 0,
  "inputs": {
    "parameters": [
      {
        "name": "Token Address"
      },
      {
        "name": "Account"
      }
    ]
  },
  "outputs": 1,
  "aliases": ["ERC20_BALANCE_OF", "ERC20BALANCEOF", "IERC20BALANCEOF"]
}

=== beehive-innovation/rain-protocol/contracts/interpreter/ops/math/logic/GreaterThan.opmeta.json
{
    "name": "GREATER_THAN",
    "desc": "Takes last 2 values from stack and puts true/1 into the stack if the first value is greater than the second value and false/0 if not.",
    "operand": [],
    "inputs": {
        "parameters": [
            {
                "name": "1st Value"
            },
            {
                "name": "2nd Value2"
            }
        ]
    },
    "outputs": 1,
    "aliases": ["GT", "GREATERTHAN", "BIGGERTHAN", "BIGGER_THAN", ">"]
}

=== beehive-innovation/rain-protocol/contracts/interpreter/ops/math/fixedPoint/FixedPointScale18.opmeta.json
{
  "name": "fp-scale18",
  "desc": "Rescale a fixed point number of N decimals to 18 decimals.",
  "operand": [
    {
      "name": "Inputs",
      "bits": [0, 2],
      "validRange": [[1, 2]]
    },
    {
      "name": "Rounding",
      "desc": "Direction to round truncation errors when scaling down. 0 = Down, 1 = Up.",
      "bits": [2, 3],
      "validRange": [[0, 1]]
    },
    {
      "name": "Current decimals",
      "desc": "Current decimals of the value being rescaled. Only used if inputs = 1.",
      "bits": [3, 15],
      "validRange": [[0, 77]]
    }
  ],
  "inputs": {
    "parameters": [
      {
        "name": "Value"
      }
    ]
  },
  "outputs": 1
}

=== beehive-innovation/rain-protocol/contracts/interpreter/ops/core/FoldContext.opmeta.json
{
    "name": "FOLD_CONTEXT",
    "desc": "Performs a looped call over some inputs and some context rows specified by folding a column as start column index and width in operand arguments as length of items in rows",
    "operand": [
        {
            "name": "Inputs",
            "bits": [12, 15],
            "validRange": [[0, 15]]
        },
        {
            "name": "Width",
            "desc": "number of columns to loop over",
            "bits": [8, 11],
            "validRange": [[0, 15]]
        },
        {
            "name": "Fold Column",
            "desc": "column to base the loop on",
            "bits": [4, 7],
            "validRange": [[0, 15]]
        },
        {
            "name": "Source Index",
            "desc": "index of the source to run",
            "bits": [0, 3],
            "validRange": [[0, 15]]
        }
    ],
    "inputs": {
        "bits": [12, 15],
        "parameters": [
            {
                "name": "Input",
                "spread": true
            }
        ]
    },
    "outputs": {
        "bits": [12, 15]
    },
    "aliases": ["FOLDCONTEXT", "FOLD"]
}
