=== beehive-innovation/rain-protocol/opmeta_schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$ref": "#/definitions/OpMeta",
    "definitions": {
        "OpMeta": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string",
                    "title": "Opcode Name",
                    "description": "The primary word used to identify the opcode",
                    "pattern": "^[A-Za-z_][0-9A-Za-z-_]*$"
                },
                "desc": {
                    "type": "string",
                    "title": "Opcode Description",
                    "description": "Describes what the opcode does briefly"
                },
                "operand": {
                    "anyOf": [
                        {
                            "type": "integer",
                            "const": 0
                        },
                        {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/OperandArg"
                            },
                            "minItems": 1
                        }
                    ],
                    "title": "Opcode Operand",
                    "description": "Data required in order to calculate and format the operand"
                },
                "inputs": {
                    "$ref": "#/definitions/InputMeta",
                    "title": "Opcode Inputs",
                    "description": "Data required to specify the inputs the opcode"
                },
                "outputs": {
                    "$ref": "#/definitions/OutputMeta",
                    "title": "Opcode Outputs",
                    "description": "Data required to specify the outputs the opcode"
                },
                "aliases": {
                    "type": "array",
                    "items": {
                        "type": "string",
                        "pattern": "^[A-Za-z_][0-9A-Za-z-_]*$"
                    },
                    "title": "Opcode Aliases",
                    "description": "Extra word used to identify the opcode"
                }
            },
            "required": [
                "name",
                "desc",
                "operand",
                "inputs",
                "outputs"
            ],
            "additionalProperties": false,
            "title": "Opcode Metadata",
            "description": "Schema for opcodes metadata used by Rainlang parser and formatter"
        },
        "OperandArg": {
            "type": "object",
            "properties": {
                "bits": {
                    "type": "array",
                    "items": {
                        "type": "integer",
                        "minimum": 0,
                        "maximum": 15
                    },
                    "minItems": 2,
                    "maxItems": 2,
                    "title": "Allocated Operand Bits",
                    "description": "Specifies the bits to allocate to this operand argument"
                },
                "name": {
                    "type": "string",
                    "title": "Operand Argument Name",
                    "description": "Name of the operand argument. Argument with the name of \"inputs\" is reserved so that it wont be be typed inside <> and its value needed to construct the operand will be the number of items inside the opcode's parens (computation will apply to this value if provided)",
                    "pattern": "^[A-Za-z0-9_][A-Za-z0-9-_\\s]*[A-Za-z0-9-_]$"
                },
                "desc": {
                    "type": "string",
                    "title": "Operand Argument Description",
                    "description": "Description of the operand argument"
                },
                "computation": {
                    "type": "string",
                    "title": "Allocated Operand Bits Computation",
                    "description": "Specifies any arithmetical operation that needs to be applied on the value of this operand argument. The \"arg\" keyword is reserved for accessing the value of this operand argument, example: \"(arg + 1) * 2\""
                },
                "validRange": {
                    "type": "array",
                    "items": {
                        "anyOf": [
                            {
                                "type": "array",
                                "items": {
                                    "type": "integer",
                                    "minimum": 0,
                                    "maximum": 65535
                                },
                                "minItems": 1,
                                "maxItems": 1
                            },
                            {
                                "type": "array",
                                "items": {
                                    "type": "integer",
                                    "minimum": 0,
                                    "maximum": 65535
                                },
                                "minItems": 2,
                                "maxItems": 2
                            }
                        ]
                    },
                    "title": "Operand Argument Range",
                    "description": "Determines the valid range of the operand argument before any computation applied. For an Operand Argument named \"Inputs\" it defines the valid length of items inside opcode's parens. For example an operand argument can be any range between 1 - 10: [[1, 10]] or an operand argument can only be certain exact number: [[2], [3], [9]], meaning it can only be 2 or 3 or 9"
                }
            },
            "required": [
                "bits",
                "name"
            ],
            "additionalProperties": false
        },
        "InputMeta": {
            "anyOf": [
                {
                    "type": "integer",
                    "const": 0
                },
                {
                    "type": "object",
                    "properties": {
                        "parameters": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "properties": {
                                    "name": {
                                        "type": "string",
                                        "title": "Input Parameter Name",
                                        "description": "Name of the input parameter",
                                        "pattern": "^[A-Za-z0-9_][A-Za-z0-9-_\\s]*[A-Za-z0-9-_]$"
                                    },
                                    "desc": {
                                        "type": "string",
                                        "title": "Input Parameter Description",
                                        "description": "Description of the input parameter"
                                    },
                                    "spread": {
                                        "type": "boolean",
                                        "title": "Parameter Spread",
                                        "description": "Specifies if an argument is dynamic in length, default is false, so only needs to be defined if an argument is spread."
                                    }
                                },
                                "required": [
                                    "name"
                                ],
                                "additionalProperties": false
                            },
                            "title": "Parameters",
                            "description": "Data type for opcode's inputs parameters, the length determines the number of inputs for constant (non-computed) inputs."
                        },
                        "bits": {
                            "type": "array",
                            "items": {
                                "type": "integer",
                                "minimum": 0,
                                "maximum": 15
                            },
                            "minItems": 2,
                            "maxItems": 2,
                            "title": "Inputs-Allocated Operand Bits",
                            "description": "Specifies bits of the operand allocated for number of inputs. Determines the number of inputs for a computed opcode inputs. Required only for computed (non-constant) inputs"
                        },
                        "computation": {
                            "type": "string",
                            "title": "Inputs-Allocated Operand Bits Computation",
                            "description": "Specifies any arithmetical operation that needs to be applied on value of the extracted operand bits. The \"bits\" keyword is reserved for accessing the exctraced value, example: \"(bits + 1) * 2\". Required only for computed (non-constant) inputs"
                        }
                    },
                    "required": [
                        "parameters"
                    ],
                    "additionalProperties": false
                }
            ]
        },
        "OutputMeta": {
            "anyOf": [
                {
                    "type": "integer",
                    "minimum": 0
                },
                {
                    "type": "object",
                    "properties": {
                        "bits": {
                            "type": "array",
                            "items": {
                                "type": "integer",
                                "minimum": 0,
                                "maximum": 15
                            },
                            "minItems": 2,
                            "maxItems": 2,
                            "title": "Outputs-Allocated Operand Bits",
                            "description": "Specifies bits of the operand allocated for number of outputs. Determines the number of outputs for a computed opcode outputs. Required only for computed (non-constant) outputs"
                        },
                        "computation": {
                            "type": "string",
                            "title": "Outputs-Allocated Operand Bits Computation",
                            "description": "Specifies any arithmetical operation that needs to be applied on value of the extracted operand bits. The \"bits\" keyword is reserved for accessing the exctraced value, example: \"(bits + 1) * 2\". Required only for computed (non-constant) outputs"
                        }
                    },
                    "additionalProperties": false
                }
            ]
        }
    }
}

=== beehive-innovation/rain-protocol/contracts/interpreter/ops/tier/OpITierV2ReportTimeForTier.opmeta.json
{
  "name": "itier-v2-report-time-for-tier",
  "desc": "Inserts the specified tier level report of an account of a tier contract and optionally contexts which are taken from the stack into the stack",
  "operand": [
    {
      "name": "Inputs",
      "bits": [0, 7],
      "validRange": [[3], [4], [11]],
      "computation": "arg - 3"
    }
  ],
  "inputs": {
    "bits": [0, 7],
    "parameters": [
      {
        "name": "ITierV2 Address"
      },
      {
        "name": "Account"
      },
      {
        "name": "Tier"
      },
      {
        "name": "Context",
        "desc": "The contextual values",
        "spread": true
      }
    ]
  },
  "outputs": 1,
  "aliases": [
    "tier-report-time-for-tier"
  ]
}

=== beehive-innovation/rain-protocol/contracts/interpreter/ops/math/logic/IsZero.opmeta.json
{
  "name": "ISZERO",
  "desc": "Checks if the value is zero and inserts true/1 into the stack if it is, else inserts false/0",
  "operand": 0,
  "inputs": {
    "parameters": [
      {
        "name": "Value"
      }
    ]
  },
  "outputs": 1,
  "aliases": ["IS_ZERO", "FALSE", "IS_FALSE", "ISFALSE"]
}

=== beehive-innovation/rain-protocol/contracts/interpreter/ops/math/fixedPoint/OpFixedPointScaleBy.opmeta.json
{
  "name": "scale-by",
  "desc": "Scale a fixed point up or down by operand.",
  "operand": [
    {
      "name": "Scale",
      "desc": "determines the up/down scale as 2s complement",
      "bits": [0, 7]
    }
  ],
  "inputs": {
    "parameters": [
      {
        "name": "Value",
        "desc": "The value to scale by"
      }
    ]
  },
  "outputs": 1,
  "aliases": ["scaleby"]
}

=== beehive-innovation/rain-protocol/contracts/interpreter/ops/rain/IVerifyV1/IVerifyV1AccountStatusAtTime.opmeta.json
{
    "name": "IVERFYV1_ACCOUNT_STATUS_AT_TIME",
    "desc": "Read and put the status of an account from the verify v1 contract into the stack",
    "operand": 0,
    "outputs": 1,
    "inputs": {
        "parameters": [
            {
                "name": "IVerifyV1 Address"
            },
            {
                "name": "Account Address"
            }
        ]
    },
    "aliases": ["VERIFY_STATUS", "VERIFYSTATUS"]
}

=== beehive-innovation/rain-protocol/contracts/interpreter/ops/erc20/snapshot/OpERC20SnapshotTotalSupplyAt.opmeta.json
{
  "name": "erc20-snapshot-total-supply-at",
  "desc": "Get the snapshot supply of an ERC20 token and insert it into the stack",
  "operand": 0,
  "inputs": {
    "parameters": [
      {
        "name": "Token Address"
      },
      {
        "name": "Snapshot Id"
      }
    ]
  },
  "outputs": 1,
  "aliases": ["erc20snapshottotalsupplyat", "ierc20snapshottotalsupplyat"]
}

=== beehive-innovation/rain-protocol/contracts/interpreter/ops/rain/ISaleV2/ISaleV2RemainingTokenInventory.opmeta.json
{
    "name": "ISALEV2_REMAINING_TOKEN_INVENTORY",
    "desc": "The remaining rTKNs left to to be sold",
    "operand": [],
    "inputs": {
        "parameters": [
            {
                "name": "ISale Address"
            }
        ]
    },
    "outputs": 1,
    "aliases": ["REMAINING_UNITS"]
}

=== beehive-innovation/rain-protocol/contracts/interpreter/ops/tier/OpSaturatingDiff.opmeta.json
{
  "name": "saturating-diff",
  "desc": "Inserts the saturating difference of 2 reports taken from the stack into the stack and prevents reverts if the result below zero",
  "operand": 0,
  "inputs": {
    "parameters": [
      {
        "name": "1st Value"
      },
      {
        "name": "2nd Value"
      }
    ]
  },
  "outputs": 1,
  "aliases": ["sat-diff", "satdiff", "saturatingdiff"]
}

=== beehive-innovation/rain-protocol/contracts/interpreter/ops/math/logic/EqualTo.opmeta.json
{
  "name": "equal-to",
  "desc": "Comapres the last 2 items of the stack together and inserts true/1 into stack if they are euqal, else inserts false/0",
  "operand": 0,
  "inputs": {
    "parameters": [
      {
        "name": "valu1"
      },
      {
        "name": "value2"
      }
    ]
  },
  "outputs": 1,
  "aliases": ["eq"]
}
